-- SUPABASE: Livro de visitas com moderação
-- Execute este script em: Supabase > SQL Editor > New query

create table if not exists public.guestbook_comments (
  id bigint generated by default as identity primary key,
  name text not null,
  comment text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

alter table public.guestbook_comments enable row level security;

drop policy if exists "Anyone can insert pending comments" on public.guestbook_comments;
drop policy if exists "Anyone can read approved comments" on public.guestbook_comments;

create policy "Anyone can insert pending comments"
on public.guestbook_comments
for insert
to anon
with check (
  status = 'pending'
  and length(trim(name)) between 2 and 80
  and length(trim(comment)) between 2 and 1200
);

create policy "Anyone can read approved comments"
on public.guestbook_comments
for select
to anon
using (status = 'approved');

-- Para aprovar:
-- 1. Vá em Table Editor > guestbook_comments.
-- 2. Mude o campo status de 'pending' para 'approved'.
-- 3. Para rejeitar, mude para 'rejected'.
